controller_manager:
  ros__parameters:
    update_rate: 1000 #  Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gazebo_joint_controller:
      type: forward_command_controller/ForwardCommandController #forward_command_controller/ForwardCommandController

gazebo_joint_controller:
  ros__parameters:
    joints:
      - FR_hip_joint
      - FR_uleg_joint
      - FR_lleg_joint
      - FL_hip_joint
      - FL_uleg_joint
      - FL_lleg_joint
      - BR_hip_joint
      - BR_uleg_joint
      - BR_lleg_joint
      - BL_hip_joint
      - BL_uleg_joint
      - BL_lleg_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
      - effort
    
    state_publish_rate: 50.0 # Hz, Defaults to 50
    action_monitor_rate: 20.0 # Hz, Defaults to 20
    
    allow_partial_joints_goal: false # Defaults to false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
    
    #gains:
     # FR_lleg_joint:
      #  p: 2147483647.0
       # i: 12.0
        #d: 100.0
    #  FL_lleg_joint:
    #    p: 2147483647.0
    #    i: 12.0
    #    d: 100.0
    #  BR_lleg_joint:
    #    p: 2147483647.0
    #    i: 12.0
    #    d: 100.0
    #  BL_lleg_joint:
    #    p: 2147483647.0
    #    i: 12.0
    #    d: 100.0 
